using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WindowsInput;
using WindowsInput.Native;
namespace AutoClicker
{
    static class VirtualKeyConverter
    {
        public static VirtualKeyCode? GetVirtualKey(string key)
        {
            return key.ToUpper() switch
            {
                "A" => VirtualKeyCode.VK_A,
                "B" => VirtualKeyCode.VK_B,
                "C" => VirtualKeyCode.VK_C,
                "D" => VirtualKeyCode.VK_D,
                "E" => VirtualKeyCode.VK_E,
                "F" => VirtualKeyCode.VK_F,
                "G" => VirtualKeyCode.VK_G,
                "H" => VirtualKeyCode.VK_H,
                "I" => VirtualKeyCode.VK_I,
                "J" => VirtualKeyCode.VK_J,
                "K" => VirtualKeyCode.VK_K,
                "L" => VirtualKeyCode.VK_L,
                "M" => VirtualKeyCode.VK_M,
                "N" => VirtualKeyCode.VK_N,
                "O" => VirtualKeyCode.VK_O,
                "P" => VirtualKeyCode.VK_P,
                "Q" => VirtualKeyCode.VK_Q,
                "R" => VirtualKeyCode.VK_R,
                "S" => VirtualKeyCode.VK_S,
                "T" => VirtualKeyCode.VK_T,
                "U" => VirtualKeyCode.VK_U,
                "V" => VirtualKeyCode.VK_V,
                "W" => VirtualKeyCode.VK_W,
                "X" => VirtualKeyCode.VK_X,
                "Y" => VirtualKeyCode.VK_Y,
                "Z" => VirtualKeyCode.VK_Z,
                "0" => VirtualKeyCode.VK_0,
                "1" => VirtualKeyCode.VK_1,
                "2" => VirtualKeyCode.VK_2,
                "3" => VirtualKeyCode.VK_3,
                "4" => VirtualKeyCode.VK_4,
                "5" => VirtualKeyCode.VK_5,
                "6" => VirtualKeyCode.VK_6,
                "7" => VirtualKeyCode.VK_7,
                "8" => VirtualKeyCode.VK_8,
                "9" => VirtualKeyCode.VK_9,
                "NUMPAD0" => VirtualKeyCode.NUMPAD0,
                "NUMPAD1" => VirtualKeyCode.NUMPAD1,
                "NUMPAD2" => VirtualKeyCode.NUMPAD2,
                "NUMPAD3" => VirtualKeyCode.NUMPAD3,
                "NUMPAD4" => VirtualKeyCode.NUMPAD4,
                "NUMPAD5" => VirtualKeyCode.NUMPAD5,
                "NUMPAD6" => VirtualKeyCode.NUMPAD6,
                "NUMPAD7" => VirtualKeyCode.NUMPAD7,
                "NUMPAD8" => VirtualKeyCode.NUMPAD8,
                "NUMPAD9" => VirtualKeyCode.NUMPAD9,
                "F1" => VirtualKeyCode.F1,
                "F2" => VirtualKeyCode.F2,
                "F3" => VirtualKeyCode.F3,
                "F4" => VirtualKeyCode.F4,
                "F5" => VirtualKeyCode.F5,
                "F6" => VirtualKeyCode.F6,
                "F7" => VirtualKeyCode.F7,
                "F8" => VirtualKeyCode.F8,
                "F9" => VirtualKeyCode.F9,
                "F10" => VirtualKeyCode.F10,
                "F11" => VirtualKeyCode.F11,
                "F12" => VirtualKeyCode.F12,
                "LMOUSE" => VirtualKeyCode.LBUTTON,
                "RMOUSE" => VirtualKeyCode.RBUTTON,
                "BACK" => VirtualKeyCode.BACK,
                "TAB" => VirtualKeyCode.TAB,
                "CLEAR" => VirtualKeyCode.CLEAR,
                "RETURN" => VirtualKeyCode.RETURN,
                "PAUSE" => VirtualKeyCode.PAUSE,
                "CAPITAL" => VirtualKeyCode.CAPITAL,                
                "ESCAPE" => VirtualKeyCode.ESCAPE,               
                "ACCEPT" => VirtualKeyCode.ACCEPT,                
                "SPACE" => VirtualKeyCode.SPACE,
                "PRIOR" => VirtualKeyCode.PRIOR,
                "NEXT" => VirtualKeyCode.NEXT,
                "END" => VirtualKeyCode.END,
                "HOME" => VirtualKeyCode.HOME,
                "LEFT" => VirtualKeyCode.LEFT,
                "UP" => VirtualKeyCode.UP,
                "RIGHT" => VirtualKeyCode.RIGHT,
                "DOWN" => VirtualKeyCode.DOWN,
                "INSERT" => VirtualKeyCode.INSERT,
                "DELETE" => VirtualKeyCode.DELETE,
                "LSHIFT" => VirtualKeyCode.LSHIFT,
                "RSHIFT" => VirtualKeyCode.RSHIFT,
                "LCONTROL" => VirtualKeyCode.LCONTROL,
                "RCONTROL" => VirtualKeyCode.RCONTROL,
                "LMENU" => VirtualKeyCode.LMENU,
                "RMENU" => VirtualKeyCode.RMENU,
                "OEM_PLUS" => VirtualKeyCode.OEM_PLUS,
                "OEM_COMMA" => VirtualKeyCode.OEM_COMMA,
                "OEM_MINUS" => VirtualKeyCode.OEM_MINUS,
                "OEM_PERIOD" => VirtualKeyCode.OEM_PERIOD,
                _ => null,
            };
        }
        public static string GetStringKey(VirtualKeyCode? keyCode)
        {
            return keyCode switch
            {
                VirtualKeyCode.VK_A => "A",
                VirtualKeyCode.VK_B => "B",
                VirtualKeyCode.VK_C => "C",
                VirtualKeyCode.VK_D => "D",
                VirtualKeyCode.VK_E => "E",
                VirtualKeyCode.VK_F => "F",
                VirtualKeyCode.VK_G => "G",
                VirtualKeyCode.VK_H => "H",
                VirtualKeyCode.VK_I => "I",
                VirtualKeyCode.VK_J => "J",
                VirtualKeyCode.VK_K => "K",
                VirtualKeyCode.VK_L => "L",
                VirtualKeyCode.VK_M => "M",
                VirtualKeyCode.VK_N => "N",
                VirtualKeyCode.VK_O => "O",
                VirtualKeyCode.VK_P => "P",
                VirtualKeyCode.VK_Q => "Q",
                VirtualKeyCode.VK_R => "R",
                VirtualKeyCode.VK_S => "S",
                VirtualKeyCode.VK_T => "T",
                VirtualKeyCode.VK_U => "U",
                VirtualKeyCode.VK_V => "V",
                VirtualKeyCode.VK_W => "W",
                VirtualKeyCode.VK_X => "X",
                VirtualKeyCode.VK_Y => "Y",
                VirtualKeyCode.VK_Z => "Z",
                VirtualKeyCode.VK_0 => "0",
                VirtualKeyCode.VK_1 => "1",
                VirtualKeyCode.VK_2 => "2",
                VirtualKeyCode.VK_3 => "3",
                VirtualKeyCode.VK_4 => "4",
                VirtualKeyCode.VK_5 => "5",
                VirtualKeyCode.VK_6 => "6",
                VirtualKeyCode.VK_7 => "7",
                VirtualKeyCode.VK_8 => "8",
                VirtualKeyCode.VK_9 => "9",
                VirtualKeyCode.NUMPAD0 => "NUMPAD0",
                VirtualKeyCode.NUMPAD1 => "NUMPAD1",
                VirtualKeyCode.NUMPAD2 => "NUMPAD2",
                VirtualKeyCode.NUMPAD3 => "NUMPAD3",
                VirtualKeyCode.NUMPAD4 => "NUMPAD4",
                VirtualKeyCode.NUMPAD5 => "NUMPAD5",
                VirtualKeyCode.NUMPAD6 => "NUMPAD6",
                VirtualKeyCode.NUMPAD7 => "NUMPAD7",
                VirtualKeyCode.NUMPAD8 => "NUMPAD8",
                VirtualKeyCode.NUMPAD9 => "NUMPAD9",
                VirtualKeyCode.F1 => "F1",
                VirtualKeyCode.F2 => "F2",
                VirtualKeyCode.F3 => "F3",
                VirtualKeyCode.F4 => "F4",
                VirtualKeyCode.F5 => "F5",
                VirtualKeyCode.F6 => "F6",
                VirtualKeyCode.F7 => "F7",
                VirtualKeyCode.F8 => "F8",
                VirtualKeyCode.F9 => "F9",
                VirtualKeyCode.F10 => "F10",
                VirtualKeyCode.F11 => "F11",
                VirtualKeyCode.F12 => "F12",
                VirtualKeyCode.LBUTTON => "LMOUSE",
                VirtualKeyCode.RBUTTON => "RMOUSE",
                VirtualKeyCode.MBUTTON => "MMOUSE",
                VirtualKeyCode.BACK => "BACK",
                VirtualKeyCode.TAB => "TAB",
                VirtualKeyCode.CLEAR => "CLEAR",
                VirtualKeyCode.RETURN => "RETURN",
                VirtualKeyCode.PAUSE => "PAUSE",              
                VirtualKeyCode.ESCAPE => "ESCAPE",
                VirtualKeyCode.SPACE => "SPACE",
                VirtualKeyCode.PRIOR => "PRIOR",
                VirtualKeyCode.NEXT => "NEXT",
                VirtualKeyCode.END => "END",
                VirtualKeyCode.HOME => "HOME",
                VirtualKeyCode.LEFT => "LEFT",
                VirtualKeyCode.UP => "UP",
                VirtualKeyCode.RIGHT => "RIGHT",
                VirtualKeyCode.DOWN => "DOWN",
                VirtualKeyCode.INSERT => "INSERT",
                VirtualKeyCode.DELETE => "DELETE",
                VirtualKeyCode.LSHIFT => "LSHIFT",
                VirtualKeyCode.RSHIFT => "RSHIFT",
                VirtualKeyCode.LCONTROL => "LCONTROL",
                VirtualKeyCode.RCONTROL => "RCONTROL",
                VirtualKeyCode.LMENU => "LMENU",
                VirtualKeyCode.RMENU => "RMENU",                
                VirtualKeyCode.OEM_PLUS => "OEM_PLUS",
                VirtualKeyCode.OEM_COMMA => "OEM_COMMA",
                VirtualKeyCode.OEM_MINUS => "OEM_MINUS",
                VirtualKeyCode.OEM_PERIOD => "OEM_PERIOD",                
                null => "",
            };
        }
    }
}
